version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - mkdir -p package
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo Preparing application files...
      # Copia todo excepto la carpeta package/ misma
      - rsync -av --exclude=package . package/
      - cd package
      - zip -r ../deploy.zip .
      - cd ..

artifacts:
  files:
    - deploy.zip
